import googleImg from './google.png';
import arrow from './arrow.png';
import googleSvg from './google.svg';
import whiteStar from './whiteStar.svg';
import blackStar from './blackStar.svg';
import tick from './tick.svg';
import like from './like.svg';
import disLike from './disLike.svg';
import closePng from './cross.png';
import copyPng from './copy.png';
import twitterPng from './twitter.png';
import discordPng from './discord.png';
import telegramPng from './telegram.png';
import giftPng from './gift.png'
import creditBannerPng from './creditBanner.png'
import creditCheck from './creditCheck.png'
import helpCenter1 from './helpCenter1.svg'
import helpCenter2 from './helpCenter2.svg'
import emailLogo from './emailLogo.svg';
import crossLogo from './cross.svg';
import alertLogo from './alert.svg';
import toastTic from './toastTick.svg';
import questionLogo from './question.svg';
import primaryCross from './primaryCross.svg';
import errorCross from './errorCross.svg';
import successCross from './successCross.svg';
import warnCross from './warnCross.svg';
import primaryAlert from './primaryAlert.svg';
import whatsappSvg from './whatsapp.svg';
import twitterSvg from './twitter.svg';
import discordSvg from './discord.svg';
import copySVG from './copy.svg';
import copyLargeSVG from './copyLarge.svg';
import userChatPng from './userChat.png';
import aiChatPng from './aiChatIcon.svg';
import sendChatPng from './sendArrow.png';
import leftArrowPng from './arroLeft.png';
import linkPng from './link.png';
import searchIcon from './search.svg';
import commandkeyIcon from './commandkey.svg';
import enterIcon from "./enter.svg"
import questLogo from "./questLogo.png";
import radioActive from "./radioActive.svg";
import radioInActive from "./radioInActive.svg";
import downArroIcon from "./downArrow.svg";
import gsTick from "./gsTick.svg";
import upArrow from "./upArrow.svg";
import closeRounded from "./closeRounded.svg"
import greenCheck from "./greenCheck.svg";
import xbutton from "./xbutton.svg"
import emailIcon from "./email.svg"
import arrowRight from "./arroRight.svg";
import pendingIcon from "./pending.svg";
export { whatsappSvg, twitterSvg, discordSvg, copySVG, googleImg, copyLargeSVG, arrow, googleSvg, whiteStar, blackStar, tick, disLike, like, closePng, copyPng, twitterPng, telegramPng, discordPng, giftPng, creditBannerPng, creditCheck, helpCenter1, helpCenter2, emailLogo, crossLogo, alertLogo, toastTic, questionLogo, warnCross, primaryCross, errorCross, successCross, primaryAlert, userChatPng, aiChatPng, sendChatPng, leftArrowPng, linkPng, searchIcon,commandkeyIcon,enterIcon,questLogo,radioActive,radioInActive,downArroIcon,gsTick,upArrow,closeRounded,greenCheck,xbutton,emailIcon,arrowRight,pendingIcon };